ngd_slim: Register with QMI service in the slave-notification thread
Slave notification thread is used to notify slaves when QMI server
(hosted by slimbus msater driver) on the remote execution environment
has come up. Use that thread's entry point to do QMI service
registration as well since doing so in probe may trigger another
probe by the QMI service leading to boot-up stalling.

Change-Id: I06b1bcfd9aa3d570554971acacd5d7b1dc20fd1c
Signed-off-by: Sagar Dharia <sdharia@codeaurora.org>
Signed-off-by: franciscofranco <franciscofranco.1990@gmail.com>

slim_msm: support non-blocking writes from slimbus MSM controller

Provide non-blocking write support so that clients can queue multiple
writes, or larger transfers without performance implications.
TX buffer is created and descriptors out of this buffer
are submitted to HW to transmit data.
Descriptor is returned to 'available' pool of TX buffer when HW
interrupt for transmission status is recieved.

Change-Id: Icc2af6bf4f770c8cadb9bd2ef7be0f95eb22c5d8
Signed-off-by: Sagar Dharia <sdharia@codeaurora.org>
Signed-off-by: franciscofranco <franciscofranco.1990@gmail.com>

slim_msm: fix LPAE builds (64-bit division)

We can't currently divide 64-bit numbers on LPAE builds. Currently,
slim-msm.c is using a physical address as part of a division operation,
resulting in the following linker error:

      LD      init/built-in.o
    drivers/built-in.o: In function `msm_slim_tx_msg_return':
    drivers/slimbus/slim-msm.c:432: \
        undefined reference to `__aeabi_uldivmod'

Fix this by casting the physical address to an unsigned long.

Change-Id: I396697158c57c80240ccd039006422afd684f47d
Signed-off-by: Mitchel Humpherys <mitchelh@codeaurora.org>
Signed-off-by: franciscofranco <franciscofranco.1990@gmail.com>

slimbus: Cleanup dev_list when device is removed

Remove a device's list-entry from controller's
device-list when that device is removed.

Signed-off-by: Naveen Kaje <nkaje@codeaurora.org>
Change-Id: I068bf34b6692dad33332f4b9baf49e768f5b2736
Signed-off-by: franciscofranco <franciscofranco.1990@gmail.com>

slim_msm: Handle ADSP SSR gracefully for apps-owned data channels

Usually the data channels are owned by codec, or by ADSP itself. If
apps itself is involved in data-transfer on the channels, make sure
the BAM pipes, or the port-registers in question are not accessed
while ADSP is restarting.

Change-Id: I9476c7389dbf89d902f0ef6572f3f755f0575f7b
Signed-off-by: Sagar Dharia <sdharia@codeaurora.org>
Signed-off-by: franciscofranco <franciscofranco.1990@gmail.com>

ngd_slim: Ignore pm_runtime_get error when runtime-pm is not enabled

Controller power-up uses different code-path when runtime-pm is not
enabled.

Change-Id: Ibe2f119fd8f43edb657f8f623879dea4730811f4
Signed-off-by: Sagar Dharia <sdharia@codeaurora.org>
Signed-off-by: franciscofranco <franciscofranco.1990@gmail.com>

slim_ngd: Use DSP before-shutdown notification for DSP SSR

QMI_SERVER_EXIT notification comes too late (after the DSP has
shutdown). This can result in unclocked access by BAM if there was
in-flight transaction. Use BEFORE_SHUTDOWN notification of SSR
framework instead to make sure in-flight transaction is finished
before DSP turns off its resources.

CRs-Fixed: 730552
Change-Id: If3c2787c74ffa7743772e5e37eac2f768e239050
Signed-off-by: Sagar Dharia <sdharia@codeaurora.org>
Signed-off-by: franciscofranco <franciscofranco.1990@gmail.com>

slim_ngd: Ensure device state consistency with runtime-pm during SSR

During ADSP SSR, client's thread calling runtime-pm resume will
fail since ADSP is unreachable. Make sure such power-up/resume attempt
is blocked until ADSP comes up by using mutex during device-state
transition.

Change-Id: Ie85e52bb2974aaee9654eb8fa1cc60fe37c61b75
Signed-off-by: Sagar Dharia <sdharia@codeaurora.org>
Signed-off-by: franciscofranco <franciscofranco.1990@gmail.com>

slim_ngd: Avoid unnecessary pipe connect/disconnect for msg queues

If slimbus satellite device retains its logical address after power
vote, it is safe to assume that BAM HW did not get reinitialized.
Use that logic to disconnect TX/RX message queues to avoid
disconnecting and reconnecting them during every power up/down vote

Change-Id: I906c4f5f01ed076066a084a8aa10d8e4d4825e33
Signed-off-by: Sagar Dharia <sdharia@codeaurora.org>
Signed-off-by: franciscofranco <franciscofranco.1990@gmail.com>

slim_msm: effective management of data ports

The current implementaion of data ports management
assumes that the ports are allocated contiguously,
which is not a correct assumption.
This patch addresses this limitation and handles
the data ports which are allocated non-contiguously.

Change-Id: I04e83bc525a50db4d0a37028498be848af018bb5
Signed-off-by: Kiran Gunda <kgunda@codeaurora.org>
Signed-off-by: Sagar Dharia <sdharia@codeaurora.org>
Signed-off-by: franciscofranco <franciscofranco.1990@gmail.com>

slim_ngd: Handle invalid/timeout TX errors gracefully

Invalid transactions can cause timeout or NACK TX errors.
Clear completion object reference for pending TX messages and print
TX BAM pipe descriptors and status registers for such transactions.
TX timeouts during connect/disconnect port error conditions should
clear completion object reference for acklowledgement receipt
to avoid referring to stale completion object later.

Change-Id: I81018df8cab59b43753c46c8a49a5066b794fda6
Signed-off-by: Sagar Dharia <sdharia@codeaurora.org>
Signed-off-by: franciscofranco <franciscofranco.1990@gmail.com>